name = "AdmittanceModels"
uuid = "5eda1363-42a2-4d75-bc45-7e2a4a7b92b2"
authors = ["Rigetti Computing", "H-Fukagawa <あなたのEmailなど>"] # 元の作者 + あなた（フォークする場合）
version = "0.3.0-DEV" # 更新版であることがわかるバージョン名（例）

# パッケージの直接の依存関係 (標準ライブラリを除く場合もある)
[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
MatrixNetworks = "4f449596-a032-5618-b826-5a251cb6dc11"
UniqueVectors = "2fbcfb34-fd0c-5fbb-b5d7-e826d8f5b0a9"
# 標準ライブラリ (明示的に書いておく例)
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

# 互換性情報 (ここを現代的に更新)
[compat]
# Julia 本体: LTS バージョン 1.6 以降、最新の 1.x 系までを想定
julia = "1.6 - 1.12"

# 依存パッケージの互換バージョン (現在の安定版を想定した例)
Combinatorics = "1"         # v1.x 系
IterativeSolvers = "1"    # v1.x 系 (要確認)
MatrixNetworks = "1"      # v1.x 系 (要確認, 更新が止まっている可能性あり)
UniqueVectors = "1"       # v1.x 系 (要確認)
# 標準ライブラリ (Julia 1.6以降はv1.x なので "1" で良い)
LinearAlgebra = "1"
SparseArrays = "1"

# テスト用の依存関係
[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
